{% set name = "GB-code" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/GB_code-{{ version }}.tar.gz
  sha256: 9e94a011a59700f25144e93149ab38b2493f51ff9910d9ef37d01e4517112011
  patches:
    - import.patch

build:
  number: 1
  noarch: python
  entry_points:
    - csl_generator = gb_code.csl_generator:main
    - gb_generator = gb_code.gb_generator:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.14.0
    - python >={{ python_min }}
    - pyyaml

test:
  imports:
    - gb_code
  commands:
    - pip check
    - csl_generator --help
    - gb_generator
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/oekosheri/GB_code
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Grainboundary generation code'
  description: |
    This python package helps you create orthogonal grain boundary
    supercells for atomistic calculations. The code is based on the
    coincident site lattice (CSL) formulations for cubic materials 
    (sc, bcc, fcc, diamond).
  doc_url: https://github.com/oekosheri/GB_code
  dev_url: https://github.com/oekosheri/GB_code

extra:
  recipe-maintainers:
    - jan-janssen
